version: '3'
services:
  elk:
    image: sebp/elk:622
    container_name: elk
    ports:
      - 5601:5601 # kibana
      - 9200:9200 # elasticsearch
      # - 5044:5044 # logstash - not using
    environment:
      - "MAX_MAP_COUNT=${MAX_MAP_COUNT}"
